const defaultData = {
    "position": {
        "left": "10%",
        "top": "10%",
        "width": "50%",
        "height": "80%",
    },
    "moduleName": "bar_type_two",
    "delayTime": 1000,
    "style": {
        "columnNum": "1",
        "columnGap": "10",
        "rowGap": "4",
        "fontColor": "#fff",
        "itemBackground": "#5179bb",
        "barColor": "#ff9079",
        "nameFloat": "left",
        "numFloat": "right",
        "itemPaddingLeft": "5px",
        "itemPaddingRight": "5px",
        "nameFontSize": "1.8vh",
        "nameFontColor": "#fff",
        "numFontSize": "1vh",
        "numFontColor": "#fff",
        "border": "2px",
        "borderColor": "#0ff",
        "borderStyle": "solid",
        "littleItemBackground":"#636363",
        "littleItemPaddingLeft":'5px',
        "littleItemPaddingRight":'5px',
        "littleborderColor":"0",
        "littleBorderStyle": "0",
        "littleBorder": "1px",
        "littleMargin":"1%",
        "littleNameFontColor": "#fff",
        "firstColor":'#228B22',
        "secondColor":'#87CEFA',
        "thirdColor":"#FFFFE0",
        "fourthColor":"#FFA07A",
        "lineWidth":"15%",
    },
    "dataSources" : {
        "remark":"",
        "interact": [],
        "dataType": 1,
        "dataUrl": 'http://localhost:8080/fyDisplaySystem/olap/getOlapData',
        "dataParams": '{"id":62}',
        "defaultData": '{"ids":["a","b","330102004000","330102008000","330102009000","330102010000"],"legends":["成本","总收入"],"series":[[71,51,31,21],[71,51,31,21],[71,51,31,21],[71,51,31,21],[71,51,31,21],[71,51,31,21]],"title":"","xAxis":["望江","清波","紫阳","小营","湖滨","南星"]}'
    },
};
export default defaultData;