export const Components = [{
    "name": "图表",
    "menuList": [{
        "name": "柱图",
        "components": [{
            "name": "基础柱图",
            "moduleName": "echarts_bar"
        }, {
            "name": "图片柱图列表",
            "moduleName": "pic_bar_list"
        }, {
            "name": "柱图1",
            "moduleName": "bar_type_one"
        }, {
            "name": "柱图2",
            "moduleName": "bar_type_two"
        }, {
            "name": "柱图3",
            "moduleName": "bar_type_three"
        }, {
            "name": "svg柱图1",
            "moduleName": "bar_svg_type_one"
        }, {
            "name": "3D柱图(highCharts",
            "moduleName": "high_charts_bar"
        }]
    }, {
        "name": "折线图",
        "components": [{
            "name": "基础折线图",
            "moduleName": "echarts_line"
        }, {
            "name": "特殊折线图一",
            "moduleName": "line_type_one"
        }]
    }, {
        "name": "饼图",
        "components": [{
            "name": "基础饼图",
            "moduleName": "echarts_pie"
        }, {
            "name": "antv饼图",
            "moduleName": "antv_pie"
        }, {
            "name": "3d饼图(highCharts",
            "moduleName": "high_charts_pie"
        }, {
            "name": "饼图列表",
            "moduleName": "echarts_pie_list"
        }, {
            "name": "多环饼图",
            "moduleName": "echarts_ring_pie"
        }, {
            "name": "svg圆环",
            "moduleName": "svg_pie"
        }, {
            "name": "3D环形图",
            "moduleName": "high_charts_ring_pie"
        }, {
            "name": "3D锥图",
            "moduleName": "three_pyramid"
        }, {
            "name": "3D饼图",
            "moduleName": "three_pie"
        }, {
            "name": "方形占比图",
            "moduleName": "rect_pie"
        }]
    }, {
        "name": "雷达图",
        "components": [{
            "name": "基础雷达图",
            "moduleName": "echarts_radar"
        }]
    }, {
        "name": "仪表图",
        "components": [{
            "name": "基础仪表图",
            "moduleName": "echarts_gauge"
        }, {
            "name": "仪表图列表",
            "moduleName": "echarts_gauge_list"
        }]
    }, {
        "name": "词云",
        "components": [{
            "name": "词云",
            "moduleName": "word_cloud"
        }, {
            "name": "测试",
            "moduleName": "test"
        }]
    }, {
        "name": "波浪图",
        "components": [{
            "name": "波浪图",
            "moduleName": "echarts_wave_chart"
        }]
    }, {
        "name": "关系图",
        "components": [{
            "name": "关系图一",
            "moduleName": "echarts_diagram_one"
        }, {
            "name": "关系图二",
            "moduleName": "echarts_diagram_two"
        }, {
            "name": "规则引擎图",
            "moduleName": "echarts_graph_one"
        }]
    }]
}, {
    "name": "特殊",
    "menuList": [{
        "name": "标题",
        "components": [{
            "name": "多级标题",
            "moduleName": "title_multilevel"
        }, {
            "name": "警告标题",
            "moduleName": "title_warning"
        }, {
            "name": "标题带背景",
            "moduleName": "title_with_bg"
        }, {
            "name": "时间天气",
            "moduleName": "time_weather"
        }, {
            "name": "图片",
            "moduleName": "image"
        }, {
            "name": "svg标题（温州公安",
            "moduleName": "title_wzga"
        }, {
            "name": "文字",
            "moduleName": "text"
        }]
    }, {
        "name": "列表",
        "components": [{
            "name": "表格状分页列表",
            "moduleName": "table_list"
        }, {
            "name": "带图标统计列表",
            "moduleName": "num_img_list"
        }, {
            "name": "排序列表",
            "moduleName": "order_list"
        }, {
            "name": "标题列表",
            "moduleName": "sort_list"
        }, {
            "name": "antd表格列表",
            "moduleName": "antd_table"
        }, {
            "name": "菜单列表",
            "moduleName": "menu_button"
        }, {
            "name": "菜单列表（温州公安",
            "moduleName": "menu_button_wzga"
        }, {
            "name": "菜单列表（金海危化",
            "moduleName": "menu_button_jhwh"
        }, {
            "name": "统计列表类型一",
            "moduleName": "name_num_type_one"
        }, {
            "name": "统计列表类型二",
            "moduleName": "name_num_type_two"
        }, {
            "name": "统计列表类型三",
            "moduleName": "name_num_type_three"
        }, {
            "name": "统计列表类型四",
            "moduleName": "name_num_type_four"
        }, {
            "name": "统计列表类型五",
            "moduleName": "name_num_type_five"
        }, {
            "name": "统计列表类型六",
            "moduleName": "name_num_type_six"
        }, {
            "name": "统计列表类型七",
            "moduleName": "name_num_type_seven"
        }, {
            "name": "统计列表类型八",
            "moduleName": "name_num_type_eight"
        }, {
            "name": "统计列表类型九",
            "moduleName": "name_num_type_nine"
        }, {
            "name": "统计列表类型十",
            "moduleName": "name_num_type_ten"
        }, {
            "name": "统计列表类型十一",
            "moduleName": "name_num_type_eleven"
        }, {
            "name": "统计列表类型十二",
            "moduleName": "name_num_type_twelve"
        }, {
            "name": "统计列表类型十三",
            "moduleName": "name_num_type_thirteen"
        }, {
            "name": "统计列表类型十四",
            "moduleName": "name_num_type_fourteen"
        }, {
            "name": "统计列表类型十五",
            "moduleName": "name_num_type_fifteen"
        }, {
            "name": "统计列表类型十六",
            "moduleName": "name_num_type_sixteen"
        }, {
            "name": "统计列表类型十七",
            "moduleName": "name_num_type_seventeen"
        }, {
            "name": "统计列表类型十八",
            "moduleName": "name_num_type_eighteen"
        }, {
            "name": "统计列表类型十九",
            "moduleName": "name_num_type_nineteen"
        }, {
            "name": "统计列表类型二十",
            "moduleName": "name_num_type_twenty"
        }, {
            "name": "统计列表类型二十一",
            "moduleName": "name_num_type_twentyOne"
        }, {
            "name": "统计列表类型二十二",
            "moduleName": "name_num_type_twentyTwo"
        }, {
            "name": "统计列表类型二十三",
            "moduleName": "name_num_type_twentyThree"
        }, {
            "name": "统计列表类型二十四",
            "moduleName": "name_num_type_twentyFour"
        }, {
            "name": "统计列表类型二十五",
            "moduleName": "name_num_type_twentyFive"
        }, {
            "name": "统计列表类型二十六",
            "moduleName": "name_num_type_twentySix"
        }, {
            "name": "统计列表类型二十七",
            "moduleName": "name_num_type_twentySeven"
        }, {
            "name": "统计列表类型二十八",
            "moduleName": "name_num_type_twentyEight"
        }, {
            "name": "时间轴列表",
            "moduleName": "timeline"
        }, {
            "name": "名称图标列表",
            "moduleName": "name_img_list"
        }, {
            "name": "值列表",
            "moduleName": "num_split"
        }, {
            "name": "统计列表带图表",
            "moduleName": "name_num_with_chart"
        }, {
            "name": "滚动列表类型一",
            "moduleName": "list_roll_type_one"
        }, {
            "name": "滚动列表类型二",
            "moduleName": "list_roll_type_two"
        }, {
            "name": "滚动列表类型三",
            "moduleName": "list_roll_type_three"
        }, {
            "name": "滚动列表类型四",
            "moduleName": "list_roll_type_four"
        }, {
            "name": "名称列表类型一",
            "moduleName": "name_list_type_one"
        }, {
            "name": "树结构列表",
            "moduleName": "tree_list"
        }, {
            "name": "下拉框",
            "moduleName": "drop_down_box"
        }, {
            "name": "表格",
            "moduleName": "table_box"
        }, {
            "name": "可滚动列表",
            "moduleName": "scroll_table"
        }, {
            "name": "3d画廊",
            "moduleName": "gallery"
        }]
    }, {
        "name": "选择",
        "components": [{
            //     "name": "日期选择(类型一",
            //     "moduleName": "date_picker_type_one"
            // }, {
            "name": "日期加选择框筛选",
            "moduleName": "time_select_search"
        }, {
            "name": "日期区间筛选",
            "moduleName": "antd_time_search"
        }, {
            "name": "日期区间筛选二",
            "moduleName": "antd_range_picker"
        }, {
            "name": "日期筛选",
            "moduleName": "antd_time_search_one"
        }, {
            "name": "选择菜单(类型一",
            "moduleName": "menu_select_list"
        }, {
            "name": "antd级联选择",
            "moduleName": "antd_cascader"
        }, {
            "name": "antd下拉选择",
            "moduleName": "antd_select"
        }, {
            "name": "搜索",
            "moduleName": "text_search"
        }]
    }, {
        "name": "详情",
        "components": [{
            "name": "预警人员详情",
            "moduleName": "detail_people_early_warning"
        }, {
            "name": "重点人员详情",
            "moduleName": "detail_people"
        }, {
            "name": "预警事件详情",
            "moduleName": "detail_event_early_warning"
        }, {
            "name": "协同事件详情",
            "moduleName": "detail_event_synergy"
        }, {
            "name": "重点事件详情",
            "moduleName": "detail_event"
        }, {
            "name": "预警部位详情",
            "moduleName": "detail_area_early_warning"
        }, {
            "name": "预警企业详情",
            "moduleName": "detail_enterprise_early_warning"
        }, {
            "name": "应急事件详情",
            "moduleName": "detail_event_emergency"
        }, {
            "name": "流程详情",
            "moduleName": "detail_process"
        }, {
            "name": "流程内容详情",
            "moduleName": "detail_content_process"
        }, {
            "name": "重点事件详情（苍南",
            "moduleName": "detail_event_cangnan"
        }, {
            "name": "重点场所详情（苍南",
            "moduleName": "detail_area_cangnan"
        }, {
            "name": "协同事件详情（苍南",
            "moduleName": "detail_event_handle_cangnan"
        }, {
            "name": "网格负责人信息（市监局",
            "moduleName": "detail_type_one"
        }, {
            "name": "物品详情（温州公安",
            "moduleName": "detail_goods"
        }, {
            "name": "车辆详情（温州公安",
            "moduleName": "detail_car"
        }, {
            "name": "采购项目详情（温州公安",
            "moduleName": "detail_procurement_project"
        }, {
            "name": "小框详情（温州公安",
            "moduleName": "detail_car_people"
        }, {
            "name": "人员详情（瑞安",
            "moduleName": "detail_people_ruian"
        }, {
            "name": "详情",
            "moduleName": "detail"
        }]
    }, {
        "name": "弹出层",
        "components": [{
            "name": "搜索列表",
            "moduleName": "search_list_type_one"
        }, {
            "name": "详情",
            "moduleName": "popup_detail"
        }, {
            "name": "综合导航页",
            "moduleName": "navigation_page"
        }, {
            "name": "程序弹框",
            "moduleName": "program_window"
        }]
    }, {
        "name": "背景框盒",
        "components": [{
            "name": "带标题框",
            "moduleName": "box_with_title"
        }, {
            "name": "背景框（类型一",
            "moduleName": "box_type_one"
        }, {
            "name": "背景框（类型二",
            "moduleName": "box_type_two"
        }, {
            "name": "背景框（类型三",
            "moduleName": "box_type_three"
        }, {
            "name": "背景框（类型四",
            "moduleName": "box_type_four"
        }, {
            "name": "背景框（类型五",
            "moduleName": "box_type_five"
        }, {
            "name": "背景框（类型六",
            "moduleName": "box_type_six"
        }, {
            "name": "背景框（总",
            "moduleName": "box_ex"
        }, {
            "name": "iframe",
            "moduleName": "iframe_content"
        }, {
            "name": "金海危化地图",
            "moduleName": "iframe_jhwh"
        }, {
            "name": "乐清3d地图",
            "moduleName": "iframe_yueqing_map"
        }]
    }, {
        "name": "地图",
        "components": [{
            "name": "通用地图",
            "moduleName": "arc_gis_map"
        }, {
            "name": "通用地图3d",
            "moduleName": "arc_gis_map4"
        }, {
            "name": "arcGis地图(乐清",
            "moduleName": "arc_gis_map_two"
        }, {
            "name": "echarts地图",
            "moduleName": "echarts_map"
        }, {
            "name": "图片地图",
            "moduleName": "map_img"
        }, {
            "name": "svg地图",
            "moduleName": "svg_map"
        }, {
            "name": "svg地图（总",
            "moduleName": "svg_map_box"
        }, {
            "name": "svg地图（新",
            "moduleName": "svg_map_ex"
        }, {
            "name": "svg地图（临安",
            "moduleName": "svg_map_linan"
        }, {
            "name": "svg地图（临安（二版",
            "moduleName": "svg_map_linan_new"
        }, {
            "name": "svg地图（临安（三版",
            "moduleName": "svg_map_linan_ex"
        }, {
            "name": "svg地图（临安（四版",
            "moduleName": "svg_map_linan_two"
        }, {
            "name": "svg地图（大同",
            "moduleName": "svg_map_point"
        }, {
            "name": "svg地图（龙港",
            "moduleName": "svg_map_longgang"
        }, {
            "name": "svg地图（瓯海",
            "moduleName": "svg_map_ouhai"
        }, {
            "name": "svg地图（龙湾",
            "moduleName": "svg_map_longwan"
        }, {
            "name": "高德地图（温州",
            "moduleName": "map_box"
        }, {
            "name": "3D地图",
            "moduleName": "three_map"
        }, {
          "name": "svg地图（鹿城",
          "moduleName": "svg_map_lucheng"
      }, {
        "name": "arcGis地图(临平",
        "moduleName": "arc_gis_map_linping"
      }]
    }, {
        "name": "翻页",
        "components": [{
            "name": "翻页样式一",
            "moduleName": "page_type_one"
        },{
            "name": "antd分页",
            "moduleName": "antd_page"
        }]
    }, {
        "name": "ocx",
        "components": [{
            "name": "监控框",
            "moduleName": "camera"
        }, {
            "name": "单兵",
            "moduleName": "phone_tree_list"
        }, {
            "name": "雪亮工程监控（瓯海",
            "moduleName": "camera_witness"
        }, {
            "name": "雪亮工程监控（苍南",
            "moduleName": "camera_cangnan"
        }, {
            "name": "雪亮工程监控（龙港",
            "moduleName": "camera_longgang"
        }, {
            "name": "单兵（龙港",
            "moduleName": "phone_longgang"
        }, {
            "name": "监控（rtmp",
            "moduleName": "camera_video"
        }, {
            "name": "监控（flv",
            "moduleName": "camera_flv"
        }, {
            "name": "监控（hls",
            "moduleName": "camera_hls_new"
        }, {
            "name": "监控（金海危化",
            "moduleName": "camera_jhwh"
        }, {
            "name": "监控列表（金海危化",
            "moduleName": "camera_jhwh_list"
        }, {
            "name": "监控单窗口（金海危化",
            "moduleName": "camera_jhwh_one"
        }, {
          "name": "天目智矫监控（临时",
          "moduleName": "camera_tmzj"
        }]
    }, {
        "name": "hls",
        "components": [{
            "name": "阳光厨房监控",
            "moduleName": "camera_hls"
        }]
    }, {
        "name": "其他",
        "components": [{
            "name": "空白组件",
            "moduleName": "blank"
        }, {
            "name": "分割线",
            "moduleName": "line_split"
        }, {
            "name": "一键响应",
            "moduleName": "emergency_response"
        }, {
            "name": "应急处理",
            "moduleName": "emergency_response_doing"
        }, {
            "name": "登录（苍南",
            "moduleName": "login_cangnan"
        },{
            "name": "登录（临安瞭望哨",
            "moduleName": "login_linan"
        }, {
            "name": "登录（龙港",
            "moduleName": "login_longgang"
        }, {
            "name": "页面跳转按钮",
            "moduleName": "change_page_button"
        }, {
            "name": "楼层平面图",
            "moduleName": "floor_plan"
        }, {
            "name": "柳市建筑图",
            "moduleName": "three_liushi_build"
        }, {
            "name": "柳市建筑图2",
            "moduleName": "three_liushi_build_two"
        }, {
            "name": "3D地球",
            "moduleName": "three_earth"
        }, {
            "name": "3D文字",
            "moduleName": "three_font"
        }, {
            "name": "3D绕圈圆",
            "moduleName": "three_move_circle"
        }, {
            "name": "绕柱转动列表",
            "moduleName": "three_list_type_one"
        }, {
            "name": "3d台州流转图",
            "moduleName": "three_taizhou"
        }, {
            "name": "联动处置(瑞安",
            "moduleName": "linkage_disposal"
        }, {
            "name": "联动处置(龙湾",
            "moduleName": "linkage_disposal_lw"
        }, {
            "name": "月份滑块轴",
            "moduleName": "month_slider"
        }, {
            "name": "自动显隐列表",
            "moduleName": "list_length_chart"
        }, {
            "name": "文字滚动",
            "moduleName": "text_marquee"
        }, {
            "name": "乐清创新-科技创新列表",
            "moduleName": "yqcx_technological"
        }, {
            "name": "乐清创新-数字经济列表",
            "moduleName": "yqcx_digitalEconomy"
        }, {
            "name": "圆柱体统计图",
            "moduleName": "cylinder_list"
        }, {
            "name": "鹿城事件表格",
            "moduleName": "lucheng_event_table"
        }, {
            "name": "pdf组件",
            "moduleName": "pdf_box"
        }, {
            "name": "宁海首页",
            "moduleName": "ninghai_head"
        }, {
          "name": "普通日历显示",
          "moduleName": "normal_calendar_display"
      }, {
        "name": "鹿城大屏视频",
        "moduleName": "video_lucheng"
      }, {
        "name": "鹿城日程待办列表",
        "moduleName": "to_do_list"
      }, {
        "name": "获取地址栏code",
        "moduleName": "address_bar_code"
      }, {
        "name": "导出分析报告",
        "moduleName": "export_analysis_report"
      }]
    }]
}];